### ISSUE TITLE
Erreur avec YARN

### ISSUE THREAD

**Issue by marouanemkm** [Honoagency/recrutement-alternant-2021#1]
Bonjour, 

J'ai bien pu terminer l'exercice 2. Par contre concernant l'exercice 1, je rencontre le problème suivant avec YARN (pièce jointe)
![yarn-error](https://user-images.githubusercontent.com/71390904/128525090-ee238ece-c53d-45cc-bb11-11db1917c990.png)
J'ai bien installé yarn, et j'ai aussi installé gulp avec npm, mais impossible d'effectuer un gulp watch.

Merci pour votre aide.

**Comment by aronep6** [comment]
Idem, j'ai le même problème avec yarn, même après avoir mis à jour le path vers Python avec la commande `npm config set python`

**Comment by marouanemkm** [comment]
Problème résolu pour moi en passant sur un OS Ubuntu.
